version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errorlint
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 50
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      confidence: 0
  exclusions:
    generated: lax
    presets:
      - std-error-handling
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golang-templates/seed
